"""Add owner_id Column to artworks table

Revision ID: fa840862c001
Revises: caa4bc8e6ef6
Create Date: 2025-06-15 09:15:35.238799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa840862c001'
down_revision: Union[str, None] = 'caa4bc8e6ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    op.add_column('artworks', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.add_column('artworks', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('artworks', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.create_index(op.f('ix_artworks_title'), 'artworks', ['title'], unique=False)
    op.drop_constraint('artworks_user_id_fkey', 'artworks', type_='foreignkey')
    op.create_foreign_key(None, 'artworks', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('artworks', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'artworks', type_='foreignkey')
    op.create_foreign_key('artworks_user_id_fkey', 'artworks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_artworks_title'), table_name='artworks')
    op.alter_column('artworks', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_column('artworks', 'created_at')
    op.drop_column('artworks', 'owner_id')
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('buyer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('artwork_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('purchase_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], name='receipts_artwork_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name='receipts_buyer_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='receipts_pkey')
    )
    # ### end Alembic commands ###
